# ----------------------------------------------------------------------------#
# --------------- Win10 Specific Macros/Defs ---------------------------------#
# ----------------------------------------------------------------------------#

.PHONY: help
help: ## List of main goals
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / \
	{printf "%s - %s\n", $$1, $$2}' $(MAKEFILE_LIST)

USERNAME=$(shell whoami)
USER_UID=1000
USER_GID=100
     
PWD=$(shell echo %cd%)
CONTAINERID=$(shell type container)
RMCMD=del /f /q


   
